### ISSUE TITLE
Unable to reproduce VPOUR results

### ISSUE THREAD

**Issue by Xinghui-Li** [changdaeoh/BlackVIP#2]
We are trying to reproduce the results of VPOUR, but we failed to reproduce the results of VPOUR (Blackbox VP using SPSA-GC). For example, the result we reproduced on EUROSAT dataset is 51.1, which is far below 70.9 reported in the paper. Would you mind checking if the hyperparameters provided are correct?

**Comment by changdaeoh** [comment]
Thanks for your interest and for leading us to discover the problem.

Please remove **line 111** from vpour.py > VPOUR class > forward_backward func > `with autocast( ):`
(white-box VP, BAR, and BlackVIP are fine.)

That's a line that was mistyped during code cleanup.
We apologize for the inconvenience.

**Comment by Xinghui-Li** [comment]
Thank you for your reply. This indeed solves the problem. Do you have any idea why vpour does not work when using the autocast>
