### ISSUE TITLE
Question about running code for VPWB

### ISSUE THREAD

**Issue by bf-yang** [changdaeoh/BlackVIP#3]
I want to run the code for VP (white-box), and use the code according to your suggestion: "sh tl_bench.sh oxford_flowers 100 40.0", and I also change the tl_bench.sh file like this:
![image](https://github.com/changdaeoh/BlackVIP/assets/82997910/3fbd20a4-09af-46a7-b7e2-01f6fc5ea434)
Is it right? But it reports an error like this:
![image](https://github.com/changdaeoh/BlackVIP/assets/82997910/b195648e-41dc-44bd-a67a-4fb396bf4b28)

If I still run the code like this "sh tl_bench.sh oxford_flowers 100 0.5 0.2 0.02 1.0". It can run without errors. 
I just wonder how to evaluate VP(white-box), e.g. for oxford_flowers datasets, the parameters, and the tl_bench.sh file.

Thanks!

**Comment by changdaeoh** [comment]
Thank you for your interest, and sorry about my super lazy response..

It seems you run the code from `BlackVIP/scripts/coop/tl_bench.sh`, but as I mentioned in README, you should first move to `BlackVIP/scripts/method_name` directory. 
In your case to run VPWB, you first make sure that your current path is `BlackVIP/scripts/vpwb`, and please run the `tl_bench.sh` in `scripts/vpwb`.
